### PR TITLE
Pages with new results

### PR DESCRIPTION
**Pull request by damirpolat**
I ran all llama experiments again, including experiments on new scenarios on our university cluster and recreated html pages hosted on coseal's website. Please let me know if I missed anything.

Regards, 
Damir

### CODE REVIEW

**Comment by larskotthoff** [comment]
Hmm, there's a lot of changes here, also in the HTML. Did you have a look at the pages to see if they look ok?

**Comment by damirpolat** [comment]
Ah yes! I should have mentioned that I also added extra tabs for tables to include information on algorithm features and renamed old features to instance features.

**Comment by larskotthoff** [comment]
Thanks, merging.

**Comment by larskotthoff** [comment]
There seems to be something wrong with the colors, e.g. at https://coseal.github.io/aslib-r/scenario-pages/SAT18-EXP-ALGO/llama.html. The XMeans results also look odd. Could you have a look please?

**Comment by damirpolat** [comment]
Ah, good point! I looked into it and cluster results were meaningless for scenarios with algorithm features because I never adopted cluster function to work with them. I decided to remove them and I believe that also fixes the issue with colors. Should I open a new pull request?

**Comment by larskotthoff** [comment]
Yes, thanks!

**Pull request merged**
